//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string ItemId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ChangeUser { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string site_id { get; set; }
        public string title { get; set; }
        public string subtitle { get; set; }
        public Nullable<int> seller_id { get; set; }
        public string category_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> base_price { get; set; }
        public Nullable<decimal> original_price { get; set; }
        public string currency_id { get; set; }
        public Nullable<int> initial_quantity { get; set; }
        public Nullable<decimal> available_quantity { get; set; }
        public Nullable<decimal> sold_quantity { get; set; }
        public string buying_mode { get; set; }
        public string listing_type_id { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> stop_time { get; set; }
        public string condition { get; set; }
        public string permalink { get; set; }
        public string thumbnail { get; set; }
        public string secure_thumbnail { get; set; }
        public Nullable<bool> accepts_mercadopago { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public string seller_custom_field { get; set; }
        public bool IsPosted { get; set; }
        public string sub_status { get; set; }
        public Nullable<System.DateTime> historical_start_time { get; set; }
    }
}
